# Generated by Django 4.2.7 on 2023-11-15 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicesapp', '0004_service_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='title',
            new_name='name',
        ),
    ]
