# Generated by Django 4.2.7 on 2023-11-15 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicesapp', '0005_rename_title_service_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='name',
            new_name='title',
        ),
    ]
