# Generated by Django 3.2 on 2023-11-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicesapp', '0006_rename_name_service_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default='DEFAULT VALUE', upload_to='uploads/uploads'),
        ),
    ]
