# Generated by Django 3.2 on 2023-11-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicesapp', '0008_auto_20231117_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(default='DEFAULT VALUE', upload_to='media/static/img'),
        ),
    ]
