# Generated by Django 3.2 on 2023-11-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicesapp', '0010_remove_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='filled',
            field=models.BooleanField(),
        ),
    ]
