# Generated by Django 3.2 on 2023-11-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicesapp', '0011_alter_service_filled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='filled',
            field=models.BooleanField(default=True),
        ),
    ]
