# Generated by Django 3.2 on 2023-11-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='DEFAULT VALUE', upload_to='media/static/img'),
        ),
    ]
