# Generated by Django 3.2 on 2023-11-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='DEFAULT VALUE', upload_to='media/media/static/img'),
        ),
    ]
